Repository KnzkDev/KnzkApp, pull requests merged in 2018-03, with the labels that each got.

#32 Wip/tl
  www/css/style.css
  www/index.html
  www/js/init.js
  www/js/timeline.js
Labels: bug, enhancement

#33 feat: tutorial
  www/css/style.css
  www/img/tutorial.png
  www/index.html
  www/js/init.js
  www/js/tutorial.js
Labels: enhancement

#36 Add ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE.md
Labels: enhancement ✨, priority-low ❄️

#37 Improve html code style
  www/index.html
Labels: priority-low ❄️

#40 Update instance.js
  www/config/instance.js
Labels: instance.js ⤴

#42 Improve various things
  .editorconfig
  .gitignore
  .monaca/project_info.json
  .yarnclean
  LICENSE
  README.md
  package.json
  www/js/account.js
  www/js/bookmark.js
  www/js/components.js
  www/js/config.js
  www/js/doodle.js
  www/js/emoji.js
  www/js/init.js
  www/js/list.js
  www/js/log.js
  www/js/login.js
  www/js/music.js
  www/js/search.js
  www/js/timeline.js
  www/js/toot.js
  www/js/toot_new.js
  www/js/tutorial.js
  yarn.lock
Labels: priority-low ❄️

#43 Optimize images
  res/android/icon/xhdpi.png
  res/android/icon/xxhdpi.png
  res/android/icon/xxxhdpi.png
  res/android/screen/splash-port-hdpi.9.png
  res/android/screen/splash-port-ldpi.9.png
  res/android/screen/splash-port-mdpi.9.png
  res/android/screen/splash-port-xhdpi.9.png
  res/android/screen/splash-port-xxhdpi.9.png
  res/android/screen/splash-port-xxxhdpi.9.png
  res/ios/icon/icon-1024.png
  res/ios/screen/Default-568h@2x~iphone.png
  res/ios/screen/Default-667h.png
  res/ios/screen/Default-736h.png
  res/ios/screen/Default-Landscape-736h.png
  res/ios/screen/Default-Landscape@2x~ipad.png
  res/ios/screen/Default-Landscape~ipad.png
  res/ios/screen/Default-Portrait@2x~ipad.png
  res/ios/screen/Default-Portrait~ipad.png
  res/ios/screen/Default@2x~iphone.png
  res/ios/screen/Default@2x~universal~anyany.png
  res/ios/screen/Default~iphone.png
  res/winrt/screen/app_splash_screen_winrt.png
Labels: priority-low ❄️

#45 re-format codes
  www/config/instance.js
  www/css/custom-size.css
  www/css/enquete.css
  www/css/iphonex.css
  www/css/kirishima_markdown.css
  www/css/style.css
  www/css/theme-roller/mastodon/theme.css
  www/css/theme/dark.css
  www/css/toolbar-height.css
  www/index.html
  www/js/account.js
  www/js/bookmark.js
  www/js/components.js
  www/js/config.js
  www/js/doodle.js
  www/js/emoji.js
  www/js/init.js
  www/js/list.js
  www/js/log.js
  www/js/login.js
  www/js/music.js
  www/js/search.js
  www/js/timeline.js
  www/js/toot.js
  www/js/toot_new.js
Labels: priority-low ❄️
