Repository KnzkDev/KnzkApp, pull requests merged in 2018-05, with the labels that each got.

#54 Add license badge
  README.md
Labels: Priority-low ❄️

#55 Replace to the new logo style
  README.md
Labels: Priority-high 🔥

#56 Initial an English version of README.md
  README.md
Labels: Priority-medium 👌

#57 Add discord badge
  README.md
Labels: Priority-low ❄️

#58 Use Prettier, ESLint, Stylelint, HTMLHint
  .eslintignore
  .eslintrc.json
  .gitignore
  .htmlhintrc
  .prettierignore
  .stylelintignore
  .stylelintrc.json
  package.json
  www/css/bootstrap/bootstrap.css
  www/css/bootstrap/bootstrap.min.css
  www/css/custom-size.css
  www/css/kirishima_markdown.css
  www/css/style.css
  www/css/toolbar-height.css
  www/index.html
  yarn.lock
Labels: Improve ✨, Priority-medium 👌

#59 CircleCI
  circle.yml
Labels: Improve ✨, Priority-medium 👌

#60 Add build badge
  README.md
Labels: Priority-low ❄️

#61 Format files of the config directory
  www/config/config.sample.js
  www/config/instance.js
Labels: Priority-medium 👌

#62 Format the account.js
  www/js/account.js
Labels: Priority-medium 👌

#63 Format the bookmark.js
  www/js/bookmark.js
Labels: Priority-medium 👌

#64 Format remaining files of the js directory
  www/js/components.js
  www/js/config.js
  www/js/doodle.js
  www/js/emoji.js
  www/js/filter.js
  www/js/init.js
  www/js/list.js
  www/js/log.js
  www/js/login.js
  www/js/music.js
  www/js/notification.js
  www/js/search.js
  www/js/timeline.js
  www/js/toot.js
  www/js/toot_new.js
  www/js/tutorial.js
Labels: Priority-medium 👌

#67 Add .gitattributes
  .gitattributes
Labels: Improve ✨, Priority-low ❄️

#68 Add CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: Improve ✨, Priority-high 🔥

#69 Add i18n feature✨
  www/index.html
  www/js/account.js
  www/js/bookmark.js
  www/js/components.js
  www/js/config.js
  www/js/doodle.js
  www/js/emoji.js
  www/js/init.js
  www/js/list.js
  www/js/locale.js
  www/js/login.js
  www/js/notification.js
  www/js/search.js
  www/js/timeline.js
  www/js/toot.js
  www/js/toot_new.js
  www/js/tutorial.js
  www/lib/i18n/i18next.min.js
  www/lib/i18n/i18nextXHRBackend.min.js
  www/lib/i18n/jquery-i18next.min.js
  www/lib/twitter.relative.time.min.js
  www/locales/en.json
  www/locales/ja.json
Labels: Improve ✨, Priority-high 🔥

#70 feat: Hashtag trending
  www/css/style.css
  www/index.html
  www/js/components.js
  www/js/search.js
  www/locales/en.json
  www/locales/ja.json
Labels: Improve ✨
